monolog:
    channels: ['deprecation']

    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug

        deprecation:
            type: stream
            path: '%kernel.logs_dir%/deprecation.log'
            channels: [deprecation]
            level: notice
