<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250616092603 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial migration';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE mail_telegram_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                mail_server_path VARCHAR(255) NOT NULL,
                mail VARCHAR(255) NOT NULL,
                password VARCHAR(255) NOT NULL,
                mail_directory VARCHAR(255) DEFAULT 'INBOX' NOT NULL,
                mail_server_encoding_type VARCHAR(255) DEFAULT 'UTF-8' NOT NULL,
                user_id BIGINT NOT NULL,
                telegram_chat_id INT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX mail_telegram_user_user_id_idx ON mail_telegram_user (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE mail_telegram_user ADD CONSTRAINT FK_EBA2F255A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE mail_telegram_user DROP CONSTRAINT FK_EBA2F255A76ED395
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE mail_telegram_user
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE users
        SQL);
    }
}
