<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250618210434 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial migration';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE mail_telegram (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                mail_server_path VARCHAR(255) NOT NULL,
                mail VARCHAR(255) NOT NULL,
                password VARCHAR(255) NOT NULL,
                mail_directory VARCHAR(255) DEFAULT 'INBOX' NOT NULL,
                mail_server_encoding_type VARCHAR(255) DEFAULT 'UTF-8' NOT NULL,
                telegram_chat_id INT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            DROP TABLE mail_telegram
        SQL);
    }
}
