parameters:
    app.version: '%env(resolve:APP_VERSION)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude: '../src/{*DTO.php,*Exception.php}'

    # infrastructure
    # telegram bot
    App\Infrastructure\TelegramBot\Factory\TelegramBotClientFactoryInterface:
        alias: App\Infrastructure\TelegramBot\Factory\TelegramBotClientLoggingDecoratorFactory
    App\Infrastructure\TelegramBot\Factory\TelegramBotClientLoggingDecoratorFactory:
        decorates: App\Infrastructure\TelegramBot\Factory\TelegramBotClientFactory
    App\Infrastructure\TelegramBot\Factory\TelegramBotClientFactory: ~
    # imap
    App\Infrastructure\Imap\Factory\ImapClientFactoryInterface:
        alias: App\Infrastructure\Imap\Factory\ImapClientLoggingDecoratorFactory
    App\Infrastructure\Imap\Factory\ImapClientLoggingDecoratorFactory:
        decorates: App\Infrastructure\Imap\Factory\ImapClientFactory
    App\Infrastructure\Imap\Factory\ImapClientFactory: ~
    # persistence
    # repositories
    App\Infrastructure\Persistence\Doctrine\Repository\MailTelegram\MailTelegramRepository:
        class: App\Infrastructure\Persistence\Doctrine\Repository\MailTelegram\MailTelegramRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - App\Domain\Entity\MailTelegram\MailTelegram

    # domain
    # repositories
    App\Domain\Repository\MailTelegram\MailTelegramRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\MailTelegram\MailTelegramRepository

    # application
    # handlers
    App\Application\Http\API\Handler\Version\GetVersionHandler:
        arguments:
            $apiVersion: '%app.version%'
    # commands
    App\Application\Command\MailTelegram\MailTelegramMessageForwarderCommand:
        arguments:
            $retriesCount: '%env(resolve:MAIL_TELEGRAM_FORWARDER_RETRIES_COUNT)%'
    # services
    App\Application\Service\MailTelegram\Formatter\MailTelegramMessageFormatterInterface:
        alias: App\Application\Service\MailTelegram\Formatter\MailTelegramMessageFormatter
    App\Application\Service\MailTelegram\Formatter\MessageHeader\MailTelegramMessageHeaderFormatterInterface:
        alias: App\Application\Service\MailTelegram\Formatter\MessageHeader\MailTelegramMessageHeaderFormatter
    App\Application\Service\MailTelegram\Formatter\MessageHeader\MailTelegramMessageHeaderFormatter:
        arguments:
            $htmlTagSymbolsSanitizer: '@App\Application\Service\MailTelegram\Formatter\Sanitizer\HtmlTagSymbolsSanitizer'
    App\Application\Service\MailTelegram\Formatter\MessageBody\MailTelegramMessageBodyFormatterInterface:
        tags: [ 'app.mail_telegram_message_body_formatter' ]
    App\Application\Service\MailTelegram\Formatter\MessageBody\MailTelegramMessageBodyHtmlFormatter:
        arguments:
            $htmlTagSymbolsSanitizer: '@App\Application\Service\MailTelegram\Formatter\Sanitizer\HtmlTagSymbolsSanitizer'
        tags:
            - { name: 'app.mail_telegram_message_body_formatter', priority: 100 }
    App\Application\Service\MailTelegram\Formatter\MessageBody\MailTelegramMessageBodyTextFormatter:
        tags:
            - { name: 'app.mail_telegram_message_body_formatter', priority: 90 }
    App\Application\Service\MailTelegram\Formatter\MessageBody\MailTelegramMessageBodyFormatterRegistry:
        arguments:
            $formatters: !tagged_iterator app.mail_telegram_message_body_formatter
    App\Application\Service\MailTelegram\Formatter\Sanitizer\HtmlTagSymbolsSanitizer: ~
    App\Application\Service\MailTelegram\Forwarder\MailTelegramMessageForwarder: ~
    App\Application\Service\TelegramBot\Registry\TelegramBotClientRegistry:
        arguments:
            $telegramBotConfig:
                'mail_telegram_forwarder': '%env(resolve:MAIL_TELEGRAM_FORWARDER_BOT_TOKEN)%'
