services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude: '../src/{*DTO.php,*Exception.php}'

    # infrastructure
    # telegram bot
    App\Infrastructure\TelegramBot\Factory\TelegramBotClientFactoryInterface:
        alias: App\Infrastructure\TelegramBot\Factory\TelegramBotClientLoggingDecoratorFactory
    App\Infrastructure\TelegramBot\Factory\TelegramBotClientLoggingDecoratorFactory:
        decorates: App\Infrastructure\TelegramBot\Factory\TelegramBotClientFactory
    App\Infrastructure\TelegramBot\Factory\TelegramBotClientFactory: ~
    # imap
    App\Infrastructure\Imap\Factory\ImapClientFactoryInterface:
        alias: App\Infrastructure\Imap\Factory\ImapClientLoggingDecoratorFactory
    App\Infrastructure\Imap\Factory\ImapClientLoggingDecoratorFactory:
        decorates: App\Infrastructure\Imap\Factory\ImapClientFactory
    App\Infrastructure\Imap\Factory\ImapClientFactory: ~
    # persistence
    # repositories
    App\Infrastructure\Persistence\Doctrine\Repository\MailTelegram\MailTelegramRepository:
        class: App\Infrastructure\Persistence\Doctrine\Repository\MailTelegram\MailTelegramRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - App\Domain\Entity\MailTelegram\MailTelegram

    # domain
    # repositories
    App\Domain\Repository\MailTelegram\MailTelegramRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\MailTelegram\MailTelegramRepository

    # application
    # commands
    App\Application\Command\MailTelegram\MailTelegramMessageForwarderCommand:
        arguments:
            $retriesCount: '%env(resolve:MAIL_TELEGRAM_FORWARDER_RETRIES_COUNT)%'
    # services
    App\Application\Service\MailTelegram\Formatter\MailTelegramMessageFormatterInterface:
        alias: App\Application\Service\MailTelegram\Formatter\MailTelegramMessageFormatter
    App\Application\Service\MailTelegram\Forwarder\MailTelegramMessageForwarder: ~
    App\Application\Service\TelegramBot\Registry\TelegramBotClientRegistry:
        arguments:
            $telegramBotConfig:
                'mail_telegram_forwarder': '%env(resolve:MAIL_TELEGRAM_FORWARDER_BOT_TOKEN)%'
